CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    publication_year INT,
    author_id BIGINT,
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
        REFERENCES author(id)
);